// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/google': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google.post').default>>>>
    }
    '/api/auth/google/callback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google/callback.post').default>>>>
    }
    '/api/chat/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/send.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}